#!/usr/bin/env python
# Copyright (c) 2015 Pavel Novy. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import sys
import os

sys.path.insert(0, os.path.join(
        os.path.dirname(os.path.abspath(__file__)), '..', 'lib', 'rfl-gen'))

import rfl.proto

def Main():
    if len(sys.argv) < 2:
        print 'usage: ', sys.argv, '<rfl file>'
        return 1
    pb = open(sys.argv[1], 'rb').read()
    pkg = rfl.proto.Package()
    pkg.ParseFromString(pb[4:])

    print pkg
    return 0


if __name__ == '__main__':
    sys.exit(Main())
