set (LIBRFL_PATH ${CMAKE_CURRENT_LIST_DIR}/../..)
set (RFL_VERBOSE 0 CACHE INTERNAL "rfl-scan verbositity level" FORCE)
set (CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} ${CMAKE_CURRENT_LIST_DIR})
include (RFLMacros)
